---
# tasks file for chethan
- name: install apache
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: start the apache
  service:
    name: nginx
    state: started

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'
